package soliloquy.specs.graphics.bootstrap;

import soliloquy.specs.common.shared.SoliloquyClass;

import java.util.function.Consumer;

/**
 * <b>GraphicsCoreLoop</b>
 * <p>
 * This class starts up the most basic graphics engine infrastructure, and runs the core loop.
 * <p>
 * NB: Since this class is intended to
 *
 * @author felix.t.morgenstern
 * @version 0.0.1
 *
 */
public interface GraphicsCoreLoop extends SoliloquyClass {
    /**
     * This method starts up the most basic graphics engine infrastructure.
     * @param callback A method which accepts the window Id generated by the graphics API library
     *                 (likely OpenGL). This method is intended to continue any remaining bootstrap
     *                 methods and game startup after the basic graphics engine bootstrapping has
     *                 completed.
     * @throws IllegalArgumentException If and only if callback is null
     */
    void startup(Consumer<Long> callback) throws IllegalArgumentException;
}
